# Generated by Django 5.1 on 2024-09-02 01:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('spacestations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('volume', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('IN_TRANSIT', 'IN_TRANSIT'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=255)),
                ('shipment_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='spacestations.spacestations')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='inventory.inventory')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='spacestations.spacestations')),
            ],
        ),
    ]
